name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - front_kiosk

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/
